name: gameon
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  firebase_core: ^4.7.0
  firebase_auth: ^6.4.0
  cloud_firestore: ^6.1.0
  image_picker: ^1.1.2
  google_sign_in: ^6.2.1
  http: ^1.6.0
  flutter_image_compress: ^2.1.0
  path_provider: ^2.1.1
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  #assets:
  #  - assets/images/
  #  - assets/images/icons/