// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCzIUKG1x9n8xhEgYONq_tCQb_xCUB7DPY',
    appId: '1:416742714229:web:1dfecb8364e151d22c413c',
    messagingSenderId: '416742714229',
    projectId: 'gameon-223cd',
    authDomain: 'gameon-223cd.firebaseapp.com',
    storageBucket: 'gameon-223cd.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAzM3hw6ZYzDzRsnT8xvYRaF7dO3yLrT_Q',
    appId: '1:416742714229:android:4b75e21a90025f442c413c',
    messagingSenderId: '416742714229',
    projectId: 'gameon-223cd',
    storageBucket: 'gameon-223cd.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCzIUKG1x9n8xhEgYONq_tCQb_xCUB7DPY',
    appId: '1:416742714229:web:21fbac21bff8c1652c413c',
    messagingSenderId: '416742714229',
    projectId: 'gameon-223cd',
    authDomain: 'gameon-223cd.firebaseapp.com',
    storageBucket: 'gameon-223cd.firebasestorage.app',
  );
}
